# Changes here will be overwritten by Copier
_commit: 0.3.2
_src_path: gh:pawamoy/copier-pdm.git
author_email: pawamoy@pm.me
author_fullname: "Timoth\xE9e Mazzucotelli"
author_username: pawamoy
copyright_date: '2020'
copyright_holder: "Timoth\xE9e Mazzucotelli"
copyright_holder_email: pawamoy@pm.me
copyright_license: ISC License
project_description: Show the inter-dependencies between modules of Python packages.
project_name: Dependenpy
python_package_command_line_name: dependenpy
python_package_distribution_name: dependenpy
python_package_import_name: dependenpy
repository_name: dependenpy
repository_namespace: pawamoy
repository_provider: github.com
use_precommit: false
